// packages/organelle.ui.angular/src/index.ts
import { Particle, dco, CreateParticleUnion } from "@euglena/core";
import { ui, ccp, ACK, Exception, Log } from "@euglena/template";
import { EventEmitter, Injectable } from "@angular/core";
import { sys } from "cessnalib";

export type Sap = Particle<"Sap", { context: Context<object> }>;

@Injectable()
export class Context<State extends object> {
    stateEmitter?: EventEmitter<State>;
    tools?: {
        t: (particle: Particle) => Promise<Particle | void>;
        cp: CreateParticleUnion<ACK | Exception | Log | ui.Event>;
    };
}

let sap: Sap["data"];

export default dco<ui.UI, Sap>({
    Sap: async (p, tools) => {
        sap = p.data;
        (sap.context as any).tools = tools;
        sap.context.stateEmitter = new EventEmitter();
    },
    Render: async (p) => {
        if (sap.context.stateEmitter) {
            sap.context.stateEmitter.emit(p.data);
            return ccp("ACK");
        } else {
            return ccp("Exception", new sys.type.Exception("Organelle Angular is need its SAP"));
        }
    }
});

// packages/organelle.ui.react/src/index.tsx
import { Particle, dco, CreateParticleUnion } from "@euglena/core";
import { ui, ACK, Log, ccp } from "@euglena/template";

import React, { createContext } from "react";
import ReactDOM from "react-dom";
import { register, unregister } from "./serviceWorker";

export type Sap = Particle<"Sap", { rootComponent: typeof App; serviceWorker: boolean }>;

let App: React.FC<any>;
export const ToolsContext = createContext({
    t: {} as (particle: Particle<any>) => Promise<Particle | void>,
    cp: {} as CreateParticleUnion<ACK | Log | ui.Event>
});

export default dco<ui.UI, Sap>({
    Sap: async (p) => {
        const { rootComponent, serviceWorker } = p.data;
        App = rootComponent;
        (serviceWorker ? register : unregister)();
    },
    Render: async ({ data: props }, { t, cp }) => {
        ReactDOM.render(
            <ToolsContext.Provider value={{ t, cp }}>{App(props)}</ToolsContext.Provider>,
            document.getElementById("root")
        );
        return ccp("ACK");
    }
});
